# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/jobbsokerkompetanse
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 3000
healthcheck:
  liveness:
    path: nais/alive.txt
  readiness:
    path: nais/ready.txt